blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    HomeTemplateView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("blog/article_list/", ArticleListView.as_view(), name="article_list"),
    path("blog/article_create/", ArticleCreateView.as_view(), name="article_create"),
    path("blog/article_detail/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("blog/article/update/<int:pk>/", ArticleUpdateView.as_view(), name="article_form"),
    path("blog/article/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("", HomeTemplateView.as_view(), name="home"),

]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactsTemplateView,
    HomeTemplateView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("product_list/", ProductListView.as_view(), name="product_list"),
    path(
        "product_detail/<int:pk>/", ProductDetailView.as_view(), name="product_detail"
    ),
    path("product_create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("", HomeTemplateView.as_view(), name="home"),
    path("contacts/", ContactsTemplateView.as_view(), name="contacts"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace='catalog')),
    path("", include("blog.urls", namespace='blog')),
    path("users/", include("users.urls", namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Статья",
    )
    content = models.TextField(
        verbose_name="Содержание",
    )
    preview = models.ImageField(
        upload_to="article/images",
        verbose_name="Изображение",
        blank=True,
        null=True,
    )
    create_at = models.DateTimeField(
        auto_now_add=True,
    )
    active_is = models.BooleanField(
        verbose_name="Признак публикации",
    )
    views_counter = models.PositiveIntegerField(
        verbose_name="Количество просмотров", default=0
    )

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["views_counter"]

    def __str__(self):
        return self.title

blog/views.py
import os

from dotenv import load_dotenv
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import (
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
)

from blog.models import Article

load_dotenv(override=True)


class ArticleCreateView(CreateView):
    model = Article
    fields = ("title", "content", "views_counter", "preview", "active_is")
    template_name = 'blog/article_form.html'
    success_url = reverse_lazy("blog:article_list")


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.filter(active_is=True)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

        if self.object.views_counter == 100:
            self.send_congratulation_email()

        return self.object

    def send_congratulation_email(self):
        subject = 'Поздравляем!'
        message = f'Ваша статья {self.object.title} набрала 100 просмотров!'
        from_email = os.getenv("FROM_EMAIL")
        recipient_list = [os.getenv("RECIPIENT_EMAIL")]

        send_mail(subject, message, from_email, recipient_list)


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ("title", "content", "views_counter")
    template_name = 'blog/article_form.html'
    success_url = reverse_lazy("blog:article_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse('blog:article_detail', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blog:article_list")


class ContactsTemplateView(TemplateView):
    """Выполняет переход к странице catalog/contacts.html"""

    template_name = "catalog/contacts.html"


class HomeTemplateView(TemplateView):
    """Выполняет переход к странице catalog/contacts.html"""

    template_name = "catalog/home.html"

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-5">
            <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card">
                     <p class="card-text">Вы действительно хотите удалить {{ object.name }} ?</p>
                     <div class="card-body">
                         {% csrf_token %}
                         <button type="submit" class="btn btn-primary">
                             Удалить
                         </button>
                         <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_list' %}">Отмена</a>
                     </div>
                 </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_create.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-5">
            <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card">
                     <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                         <button type="submit" class="btn btn-primary">
                             {% if object %}
                             Создать
                             {% else %}
                             Сохранить
                             {% endif %}
                         </button>
                         <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_list' %}">Отмена</a>
                     </div>
                 </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                {% if article.preview %}
                    <img src="{{ article.preview | media_filter }}" width="150" style="height:auto;">
                {% else %}
                    <p>Нет изображения</p>
                {% endif %}
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.title }}</h2>
                </div>
                <div class="card-body">
                    <div class="fields-container m-3">
                        <div class="field">
                            <p>
                                <strong>Содержание:</strong>
                                <span>{{ object.content }}</span>
                            </p>
                        </div>
                        <div class="field">
                            <p>
                                <strong>Количество просмотров:</strong>
                                <span>{{ object.views_counter }}</span>
                            </p>
                        </div>
                    </div>
                    <p>Создано: {{ article.create_at }}</p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_form' object.pk %}">Редактировать</a>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_list' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-5">
            <form class="row" method="post" enctype="multipart/form-data">
                 <div class="card">
                     <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                         <button type="submit" class="btn btn-primary">
                             {% if not object %}
                             Создать
                             {% else %}
                             Сохранить
                             {% endif %}
                         </button>
                         <a class="p-2 btn btn-outline-primary" href="{% url 'blog:article_list' %}">Отмена</a>
                     </div>
                 </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="container">
    <h1 class="mb-4">Наши статьи</h1>
    {% if user.is_authenticated %}
    <p><a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_create' %}">Добавить статью</a></p>
    {% endif %}
    <div class="row text-center">
        {% for article in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if article.preview %}
                        <img src="{{ article.preview | media_filter }}" width="150" style="height:auto;">
                    {% else %}
                        <p>Нет изображения</p>
                    {% endif %}
                    <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">{{ article.content | truncatechars:100 }}</h3>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_detail' article.pk %}">Подробнее</a>
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:article_delete' article.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Skystore{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}
{% include 'catalog/includes/inc_header.html' %}
{% block content %}
{% endblock %}
{% include 'catalog/includes/inc_footer.html' %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <img src="{{ product.product_image | media_filter }}">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">{{ product.price }} р.</h3>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_detail' product.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}