blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    HomeTemplateView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("blog/article_list/", ArticleListView.as_view(), name="article_list"),
    path("blog/article_create/", ArticleCreateView.as_view(), name="article_create"),
    path("blog/article_detail/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("blog/article/update/<int:pk>/", ArticleUpdateView.as_view(), name="article_form"),
    path("blog/article/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("", HomeTemplateView.as_view(), name="home"),

]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactsTemplateView,
    HomeTemplateView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("product_list/", ProductListView.as_view(), name="product_list"),
    path(
        "product_detail/<int:pk>/", ProductDetailView.as_view(), name="product_detail"
    ),
    path("product_create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("", HomeTemplateView.as_view(), name="home"),
    path("contacts/", ContactsTemplateView.as_view(), name="contacts"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace='catalog')),
    path("", include("blog.urls", namespace='blog')),
    path("users/", include("users.urls", namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from .views import RegisterView, email_verification, CustomLoginView, EditProfileView, ProfileSuccessView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(template_name='users/login.html', success_url='/catalog/product_list/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:product_list'), name='logout'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('profile/success/', login_required(ProfileSuccessView.as_view()), name='profile_success'),

]

catalog/models.py
from django.conf import settings
from django.db import models


class Product(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Товар", help_text="Введите наименование товара"
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание товара"
    )
    product_image = models.ImageField(
        upload_to="products/images",
        verbose_name="Изображение",
        help_text="Загрузите изображение товара",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        max_length=100,
        verbose_name="Категория",
        help_text="Введите категорию товара",
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.FloatField(verbose_name="Цена", help_text="Введите цену товара")
    create_date = models.DateField(
        verbose_name="Дата создания",
        help_text="Введите дату создания товара",
        blank=True,
        null=True,
    )
    update_date = models.DateField(
        verbose_name="Дата последнего обновления", blank=True, null=True
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано",
        help_text="Укажите, опубликован ли товар"
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        help_text="Выберите владельца товара"
    )


    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["category", "name"]

    def __str__(self):
        return f"Наименование: {self.name}, цена: {self.price}"


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Категория",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание категории"
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name

catalog/forms.py
import os
from django import forms
from .models import Product
from django.core.exceptions import ValidationError
from PIL import Image

FORBIDDEN_WORDS=['казино','криптовалюта','крипта','биржа','дешево','бесплатно','обман','полиция','радар']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "create_date", 'update_date', "product_image", 'category',]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите наименование товара'
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите описание товара'
        })

        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите цену товара'
        })

        self.fields['create_date'].widget.attrs.update({
            'class': 'form-control'
        })

        self.fields['update_date'].widget.attrs.update({
            'class': 'form-control'
        })

        self.fields['product_image'].widget.attrs.update({
            'class': 'form-control'
        })

        self.fields['category'].widget.attrs.update({
            'class': 'form-control'
        })

    def clean_name(self):
        name = self.cleaned_data.get('name')
        for elem in FORBIDDEN_WORDS:
            if elem in name:
                raise ValidationError("В наименовании продукта не должно быть запрещенных слов")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        for elem in FORBIDDEN_WORDS:
            if elem in description:
                raise ValidationError("В описании продукта не должно быть запрещенных слов")
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise ValidationError("Цена должна быть положительным числом")
        return price

    def clean_product_image(self):
        product_image = self.cleaned_data.get('product_image')
        if product_image:
            try:
                img = Image.open(product_image)
                if img.format not in ['JPEG', 'PNG']:
                    raise ValidationError("Формат изображения должен быть JPEG или PNG.")
            except IOError:
                raise ValidationError("Ошибка открытия изображения.")

            if product_image.size > 5 * 1024 * 1024:  # Size limit of 5 MB
                raise ValidationError("Размер изображения не должен превышать 5 МБ.")

        return product_image

catalog/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from catalog.models import Product
from catalog.forms import ProductForm

class ProductListView(ListView):
    model = Product
    context_object_name = 'products'

class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy("catalog:product_list")


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy("catalog:product_list")


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")


class ContactsTemplateView(TemplateView):
    """Выполняет переход к странице catalog/contacts.html"""

    template_name = "catalog/contacts.html"


class HomeTemplateView(TemplateView):
    """Выполняет переход к странице catalog/contacts.html"""

    template_name = "catalog/home.html"

catalog/templates/catalog/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="blog/article_list">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

catalog/templates/catalog/includes/inc_header.html
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    {% if user.is_authenticated %}
        <p class="lead">Добро пожаловать на наш сайт, {{ user.email }}!</p>
    {% else %}
        <p class="lead">Добро пожаловать на наш сайт!</p>
    {% endif %}
</div>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h3 class="my-0 mr-md-auto font-weight-normal">Skystore</h3>
    <nav class="ms-5 d-flex">
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary me-2" href="http://127.0.0.1:8000/">На главную</a>
            <a class="p-2 btn btn-outline-primary me-2" href="/product_list/">Каталог</a>
            <a class="p-2 btn btn-outline-primary me-2" href="/contacts/">Контакты</a>
            <a class="p-2 btn btn-outline-primary me-2" href="/blog/article_list/">Наш блог</a>
            <a class="nav-link me-2" href="{% url 'users:edit_profile' %}">{{ user.email }}</a>
            <form id="logout-form" action="{% url 'users:logout' %}" method="POST" style="display: none;">
                {% csrf_token %}
            </form>
            <a class="p-2 btn btn-outline-primary me-2" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary me-2" href="/product_list/">Каталог</a>
            <a class="p-2 btn btn-outline-primary me-2" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary me-2" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>